### ISSUE TITLE
Спрайты

### ISSUE THREAD

**Issue by Artur-Kerchensky** [Artur-Kerchensky/RPG#9]

**Comment by aesthetics2000** [comment]
![Image](https://github.com/Artur-Kerchensky/RPG/assets/113620073/e1234c51-db5a-489d-aa0c-9eadcac4d233)





![Image](https://github.com/Artur-Kerchensky/RPG/assets/113620073/6cbec575-59d3-411e-b339-1ba8687b6a53)
